describe('runtime error', function () {
  it('throws a error', function () {
    throw new Error('error thrown on purpose')
  })
})
